properties:
  project: resource-api-jwt-server
  env: dev
  log-level: INFO

security:
  oauth2:
    resource:
      id: oauth2-resource
      token-info-uri: http://${properties.server.oauth}/oauth/check_token
      prefer-token-info: true
      filter-order: 3
    client:
      client-id: api_service
      client-secret: secret
      access-token-uri: http://${properties.server.oauth}/oauth/token
      user-authorization-uri: http://${properties.server.oauth}/oauth/authorize

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    primary:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://192.168.1.154:3306/dev_oauth?characterEncoding=UTF-8
      username: dev
      password: 1qaz@WSX
      driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
      autoCommit: true
      connectionTestQuery: SELECT 1
