properties:
  project: tcc-product-server
  env: production
  log-level: INFO

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    primary:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://192.168.1.154:3306/product?characterEncoding=UTF-8
      username: dev
      password: 1qaz@WSX
      driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
      autoCommit: true
      connectionTestQuery: SELECT 1
