rootProject.name = "Micro-Service-Lab"
include("config-server")
include("oauth-server")
include("api-server")
include("swagger-server")
include("swagger-openapi-server")
include("oauth-redis-server")
include("product-api-server")
include("resource-jwt-server")
include("eureka-server")
include("core")
